### ISSUE TITLE
how to input 2 channels img?

### ISSUE THREAD

**Issue by czh1024** [QUVA-Lab/e2cnn_experiments#1]

**Comment by Gabri95** [comment]
Hi @czh1024 

I am sorry, I did not see this issue before :(

I think this is what you are asking:

```
in_type = FieldType(gs, [gs.trivial_repr]*c)
```

where `gs` is the gspace you are interested in and `c` is the number of input channels (e.g. 2 in your case).
You can then use `in_type` to define your first convolution layer as in most models in this repository.

Does this help?

Gabriele

**Comment by czh1024** [comment]
Thanks！



***@***.***
 
From: Gabriele Cesa
Date: 2022-02-05 01:17
To: QUVA-Lab/e2cnn_experiments
CC: zihaochen; Mention
Subject: Re: [QUVA-Lab/e2cnn_experiments] how to input 2 channels img? (Issue #1)
Hi @czh1024
I am sorry, I did not see this issue before :(
I think this is what you are asking:
in_type = FieldType(gs, [gs.trivial_repr]*c)

where gs is the gspace you are interested in and c is the number of input channels (e.g. 2 in your case).
You can then use in_type to define your first convolution layer as in most models in this repository.
Does this help?
Gabriele
