### ISSUE TITLE
Differences between EXP and SFCNN models

### ISSUE THREAD

**Issue by blazejdolicki** [QUVA-Lab/e2cnn_experiments#2]
Hello,

I've tried reproducing your results, but some parts are unclear to me. For example, in `mnist_bench.sh` you seem to be using the EXP model for equivariant networks while in `mnist_final.sh` you use SFCNN model. Could you explain how do these two models differ? And what these abbreviations stand for? I couldn't find anything about that in the paper.

Thanks in advance!

**Comment by Gabri95** [comment]
Hey! 

the difference is that the EXP model is the smaller architecture we used to generate the large table with different groups / non-linearities while te SFCNN model is a larger architecture we used to reproduce the results from [Learning Steerable Filters for Rotation Equivariant CNNs](https://arxiv.org/abs/1711.07289).

In other words, EXP is the model used in Tab 3 while SFCNN is the model used in Tab 5 of our paper ([arxiv version](https://arxiv.org/pdf/1911.08251.pdf))

Hope this helps

Gabriele

**Comment by blazejdolicki** [comment]
Thanks, that clears things up!
